[package]
name = "terratranslate-plugin-runner"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
libloading.workspace = true
tokio.workspace = true
terratranslate-plugin-api = { path = "../terratranslate-plugin-api" }

